import '../css/style.css';
import { topPanel } from './UI/topPanel';
import { Garage } from './UI/garage';
import { showGarage } from './logic/showGarage';
import { UpgradeCar } from './logic/upgradeCar';
import { createCar } from './logic/createCar';
import { deleteCar } from './logic/deleteCar';
import { drive } from './logic/drive';
import { selectPage } from './logic/selectPage';
import { Race } from './logic/race';
import { showWiners } from './UI/showWiners';
import { winersTable } from './UI/winersTable';
import { sortWiners } from './UI/sortWiners';

const getTopPanel = new topPanel();
getTopPanel.createHeader();
const garage = new Garage();
garage.createGarageHead();
showGarage.show();
winersTable.winerBox();
showWiners.toWiners();
deleteCar.delete();
createCar.create();
drive.startDrive();
drive.stopDrive();
drive.resetCar();
selectPage.nextPage();
selectPage.previousPage();
new Race();
new UpgradeCar();
sortWiners.sort();
